sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_d856f77e8b36_key -iv $encrypted_d856f77e8b36_iv -in k8s-travis-deployer.json.enc -out k8s-travis-deployer.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json