apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: g1crh-com-tls
spec:
  secretName: g1crh-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: g1crh.com
  dnsNames:
    - g1crh.com
    - www.g1crh.com